site_name: Arnon Moscona
repo_url: https://github.com/arnonmoscona/monastery-docs
site_author: Arnon Moscona
theme: readthedocs
pages:
  - "Contact" : "index.md"
  - "Summary" : "summary.md"
  -  "Emplyment History" : "history.md"
  - "education.md"

