site_name : "Arnon Moscona"
repo_url : "https://github.com/arnonmoscona/resume"
site_author : "Arnon Moscona"
theme : "readthedocs"
pages :
  - "index.md"
  - "summary.md"
  - "employment-history.md"
  - "professional-services.md"
  - "education.md"
